//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18063
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_WinForm.eBox_WebServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://eboxServic.org/", ConfigurationName="eBox_WebServices.ebox_serviceSoap")]
    public interface ebox_serviceSoap {
        
        // CODEGEN: 命名空间 http://eboxServic.org/ 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://eboxServic.org/HelloWorld", ReplyAction="*")]
        Test_WinForm.eBox_WebServices.HelloWorldResponse HelloWorld(Test_WinForm.eBox_WebServices.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://eboxServic.org/add", ReplyAction="*")]
        int add(int a, int b);
        
        // CODEGEN: 命名空间 http://eboxServic.org/ 的元素名称 PhoneNo 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://eboxServic.org/Postman_Verify", ReplyAction="*")]
        Test_WinForm.eBox_WebServices.Postman_VerifyResponse Postman_Verify(Test_WinForm.eBox_WebServices.Postman_VerifyRequest request);
        
        // CODEGEN: 命名空间 http://eboxServic.org/ 的元素名称 PhoneNo 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://eboxServic.org/Manager_Verify", ReplyAction="*")]
        Test_WinForm.eBox_WebServices.Manager_VerifyResponse Manager_Verify(Test_WinForm.eBox_WebServices.Manager_VerifyRequest request);
        
        // CODEGEN: 命名空间 http://eboxServic.org/ 的元素名称 log 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://eboxServic.org/Uploadlog", ReplyAction="*")]
        Test_WinForm.eBox_WebServices.UploadlogResponse Uploadlog(Test_WinForm.eBox_WebServices.UploadlogRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://eboxServic.org/", Order=0)]
        public Test_WinForm.eBox_WebServices.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Test_WinForm.eBox_WebServices.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://eboxServic.org/", Order=0)]
        public Test_WinForm.eBox_WebServices.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Test_WinForm.eBox_WebServices.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://eboxServic.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Postman_VerifyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Postman_Verify", Namespace="http://eboxServic.org/", Order=0)]
        public Test_WinForm.eBox_WebServices.Postman_VerifyRequestBody Body;
        
        public Postman_VerifyRequest() {
        }
        
        public Postman_VerifyRequest(Test_WinForm.eBox_WebServices.Postman_VerifyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://eboxServic.org/")]
    public partial class Postman_VerifyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PhoneNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Psw;
        
        public Postman_VerifyRequestBody() {
        }
        
        public Postman_VerifyRequestBody(string PhoneNo, string Psw) {
            this.PhoneNo = PhoneNo;
            this.Psw = Psw;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Postman_VerifyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Postman_VerifyResponse", Namespace="http://eboxServic.org/", Order=0)]
        public Test_WinForm.eBox_WebServices.Postman_VerifyResponseBody Body;
        
        public Postman_VerifyResponse() {
        }
        
        public Postman_VerifyResponse(Test_WinForm.eBox_WebServices.Postman_VerifyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://eboxServic.org/")]
    public partial class Postman_VerifyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool Postman_VerifyResult;
        
        public Postman_VerifyResponseBody() {
        }
        
        public Postman_VerifyResponseBody(bool Postman_VerifyResult) {
            this.Postman_VerifyResult = Postman_VerifyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Manager_VerifyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Manager_Verify", Namespace="http://eboxServic.org/", Order=0)]
        public Test_WinForm.eBox_WebServices.Manager_VerifyRequestBody Body;
        
        public Manager_VerifyRequest() {
        }
        
        public Manager_VerifyRequest(Test_WinForm.eBox_WebServices.Manager_VerifyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://eboxServic.org/")]
    public partial class Manager_VerifyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PhoneNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Psw;
        
        public Manager_VerifyRequestBody() {
        }
        
        public Manager_VerifyRequestBody(string PhoneNo, string Psw) {
            this.PhoneNo = PhoneNo;
            this.Psw = Psw;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Manager_VerifyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Manager_VerifyResponse", Namespace="http://eboxServic.org/", Order=0)]
        public Test_WinForm.eBox_WebServices.Manager_VerifyResponseBody Body;
        
        public Manager_VerifyResponse() {
        }
        
        public Manager_VerifyResponse(Test_WinForm.eBox_WebServices.Manager_VerifyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://eboxServic.org/")]
    public partial class Manager_VerifyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool Manager_VerifyResult;
        
        public Manager_VerifyResponseBody() {
        }
        
        public Manager_VerifyResponseBody(bool Manager_VerifyResult) {
            this.Manager_VerifyResult = Manager_VerifyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadlogRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Uploadlog", Namespace="http://eboxServic.org/", Order=0)]
        public Test_WinForm.eBox_WebServices.UploadlogRequestBody Body;
        
        public UploadlogRequest() {
        }
        
        public UploadlogRequest(Test_WinForm.eBox_WebServices.UploadlogRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://eboxServic.org/")]
    public partial class UploadlogRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string log;
        
        public UploadlogRequestBody() {
        }
        
        public UploadlogRequestBody(string log) {
            this.log = log;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadlogResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadlogResponse", Namespace="http://eboxServic.org/", Order=0)]
        public Test_WinForm.eBox_WebServices.UploadlogResponseBody Body;
        
        public UploadlogResponse() {
        }
        
        public UploadlogResponse(Test_WinForm.eBox_WebServices.UploadlogResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://eboxServic.org/")]
    public partial class UploadlogResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UploadlogResult;
        
        public UploadlogResponseBody() {
        }
        
        public UploadlogResponseBody(bool UploadlogResult) {
            this.UploadlogResult = UploadlogResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ebox_serviceSoapChannel : Test_WinForm.eBox_WebServices.ebox_serviceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ebox_serviceSoapClient : System.ServiceModel.ClientBase<Test_WinForm.eBox_WebServices.ebox_serviceSoap>, Test_WinForm.eBox_WebServices.ebox_serviceSoap {
        
        public ebox_serviceSoapClient() {
        }
        
        public ebox_serviceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ebox_serviceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ebox_serviceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ebox_serviceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Test_WinForm.eBox_WebServices.HelloWorldResponse Test_WinForm.eBox_WebServices.ebox_serviceSoap.HelloWorld(Test_WinForm.eBox_WebServices.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Test_WinForm.eBox_WebServices.HelloWorldRequest inValue = new Test_WinForm.eBox_WebServices.HelloWorldRequest();
            inValue.Body = new Test_WinForm.eBox_WebServices.HelloWorldRequestBody();
            Test_WinForm.eBox_WebServices.HelloWorldResponse retVal = ((Test_WinForm.eBox_WebServices.ebox_serviceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        public int add(int a, int b) {
            return base.Channel.add(a, b);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Test_WinForm.eBox_WebServices.Postman_VerifyResponse Test_WinForm.eBox_WebServices.ebox_serviceSoap.Postman_Verify(Test_WinForm.eBox_WebServices.Postman_VerifyRequest request) {
            return base.Channel.Postman_Verify(request);
        }
        
        public bool Postman_Verify(string PhoneNo, string Psw) {
            Test_WinForm.eBox_WebServices.Postman_VerifyRequest inValue = new Test_WinForm.eBox_WebServices.Postman_VerifyRequest();
            inValue.Body = new Test_WinForm.eBox_WebServices.Postman_VerifyRequestBody();
            inValue.Body.PhoneNo = PhoneNo;
            inValue.Body.Psw = Psw;
            Test_WinForm.eBox_WebServices.Postman_VerifyResponse retVal = ((Test_WinForm.eBox_WebServices.ebox_serviceSoap)(this)).Postman_Verify(inValue);
            return retVal.Body.Postman_VerifyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Test_WinForm.eBox_WebServices.Manager_VerifyResponse Test_WinForm.eBox_WebServices.ebox_serviceSoap.Manager_Verify(Test_WinForm.eBox_WebServices.Manager_VerifyRequest request) {
            return base.Channel.Manager_Verify(request);
        }
        
        public bool Manager_Verify(string PhoneNo, string Psw) {
            Test_WinForm.eBox_WebServices.Manager_VerifyRequest inValue = new Test_WinForm.eBox_WebServices.Manager_VerifyRequest();
            inValue.Body = new Test_WinForm.eBox_WebServices.Manager_VerifyRequestBody();
            inValue.Body.PhoneNo = PhoneNo;
            inValue.Body.Psw = Psw;
            Test_WinForm.eBox_WebServices.Manager_VerifyResponse retVal = ((Test_WinForm.eBox_WebServices.ebox_serviceSoap)(this)).Manager_Verify(inValue);
            return retVal.Body.Manager_VerifyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Test_WinForm.eBox_WebServices.UploadlogResponse Test_WinForm.eBox_WebServices.ebox_serviceSoap.Uploadlog(Test_WinForm.eBox_WebServices.UploadlogRequest request) {
            return base.Channel.Uploadlog(request);
        }
        
        public bool Uploadlog(string log) {
            Test_WinForm.eBox_WebServices.UploadlogRequest inValue = new Test_WinForm.eBox_WebServices.UploadlogRequest();
            inValue.Body = new Test_WinForm.eBox_WebServices.UploadlogRequestBody();
            inValue.Body.log = log;
            Test_WinForm.eBox_WebServices.UploadlogResponse retVal = ((Test_WinForm.eBox_WebServices.ebox_serviceSoap)(this)).Uploadlog(inValue);
            return retVal.Body.UploadlogResult;
        }
    }
}
