//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18063
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebox_client.ebox_webservice {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://eboxServic.org/", ConfigurationName="ebox_webservice.ebox_serviceSoap")]
    public interface ebox_serviceSoap {
        
        // CODEGEN: 命名空间 http://eboxServic.org/ 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://eboxServic.org/HelloWorld", ReplyAction="*")]
        ebox_client.ebox_webservice.HelloWorldResponse HelloWorld(ebox_client.ebox_webservice.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://eboxServic.org/add", ReplyAction="*")]
        int add(int a, int b);
        
        // CODEGEN: 命名空间 http://eboxServic.org/ 的元素名称 PhoneNo 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://eboxServic.org/Verify_Postman", ReplyAction="*")]
        ebox_client.ebox_webservice.Verify_PostmanResponse Verify_Postman(ebox_client.ebox_webservice.Verify_PostmanRequest request);
        
        // CODEGEN: 命名空间 http://eboxServic.org/ 的元素名称 PhoneNo 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://eboxServic.org/Verify_Manager", ReplyAction="*")]
        ebox_client.ebox_webservice.Verify_ManagerResponse Verify_Manager(ebox_client.ebox_webservice.Verify_ManagerRequest request);
        
        // CODEGEN: 命名空间 http://eboxServic.org/ 的元素名称 log 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://eboxServic.org/UploadPkglogItem", ReplyAction="*")]
        ebox_client.ebox_webservice.UploadPkglogItemResponse UploadPkglogItem(ebox_client.ebox_webservice.UploadPkglogItemRequest request);
        
        // CODEGEN: 命名空间 http://eboxServic.org/ 的元素名称 PhoneNo 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://eboxServic.org/Register_Postman", ReplyAction="*")]
        ebox_client.ebox_webservice.Register_PostmanResponse Register_Postman(ebox_client.ebox_webservice.Register_PostmanRequest request);
        
        // CODEGEN: 命名空间 http://eboxServic.org/ 的元素名称 PhoneNo 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://eboxServic.org/Postman_Spend", ReplyAction="*")]
        ebox_client.ebox_webservice.Postman_SpendResponse Postman_Spend(ebox_client.ebox_webservice.Postman_SpendRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://eboxServic.org/", Order=0)]
        public ebox_client.ebox_webservice.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ebox_client.ebox_webservice.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://eboxServic.org/", Order=0)]
        public ebox_client.ebox_webservice.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ebox_client.ebox_webservice.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://eboxServic.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Verify_PostmanRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Verify_Postman", Namespace="http://eboxServic.org/", Order=0)]
        public ebox_client.ebox_webservice.Verify_PostmanRequestBody Body;
        
        public Verify_PostmanRequest() {
        }
        
        public Verify_PostmanRequest(ebox_client.ebox_webservice.Verify_PostmanRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://eboxServic.org/")]
    public partial class Verify_PostmanRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PhoneNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Psw;
        
        public Verify_PostmanRequestBody() {
        }
        
        public Verify_PostmanRequestBody(string PhoneNo, string Psw) {
            this.PhoneNo = PhoneNo;
            this.Psw = Psw;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Verify_PostmanResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Verify_PostmanResponse", Namespace="http://eboxServic.org/", Order=0)]
        public ebox_client.ebox_webservice.Verify_PostmanResponseBody Body;
        
        public Verify_PostmanResponse() {
        }
        
        public Verify_PostmanResponse(ebox_client.ebox_webservice.Verify_PostmanResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://eboxServic.org/")]
    public partial class Verify_PostmanResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Verify_PostmanResult;
        
        public Verify_PostmanResponseBody() {
        }
        
        public Verify_PostmanResponseBody(int Verify_PostmanResult) {
            this.Verify_PostmanResult = Verify_PostmanResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Verify_ManagerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Verify_Manager", Namespace="http://eboxServic.org/", Order=0)]
        public ebox_client.ebox_webservice.Verify_ManagerRequestBody Body;
        
        public Verify_ManagerRequest() {
        }
        
        public Verify_ManagerRequest(ebox_client.ebox_webservice.Verify_ManagerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://eboxServic.org/")]
    public partial class Verify_ManagerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PhoneNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Psw;
        
        public Verify_ManagerRequestBody() {
        }
        
        public Verify_ManagerRequestBody(string PhoneNo, string Psw) {
            this.PhoneNo = PhoneNo;
            this.Psw = Psw;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Verify_ManagerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Verify_ManagerResponse", Namespace="http://eboxServic.org/", Order=0)]
        public ebox_client.ebox_webservice.Verify_ManagerResponseBody Body;
        
        public Verify_ManagerResponse() {
        }
        
        public Verify_ManagerResponse(ebox_client.ebox_webservice.Verify_ManagerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://eboxServic.org/")]
    public partial class Verify_ManagerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool Verify_ManagerResult;
        
        public Verify_ManagerResponseBody() {
        }
        
        public Verify_ManagerResponseBody(bool Verify_ManagerResult) {
            this.Verify_ManagerResult = Verify_ManagerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadPkglogItemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadPkglogItem", Namespace="http://eboxServic.org/", Order=0)]
        public ebox_client.ebox_webservice.UploadPkglogItemRequestBody Body;
        
        public UploadPkglogItemRequest() {
        }
        
        public UploadPkglogItemRequest(ebox_client.ebox_webservice.UploadPkglogItemRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://eboxServic.org/")]
    public partial class UploadPkglogItemRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string log;
        
        public UploadPkglogItemRequestBody() {
        }
        
        public UploadPkglogItemRequestBody(string log) {
            this.log = log;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadPkglogItemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadPkglogItemResponse", Namespace="http://eboxServic.org/", Order=0)]
        public ebox_client.ebox_webservice.UploadPkglogItemResponseBody Body;
        
        public UploadPkglogItemResponse() {
        }
        
        public UploadPkglogItemResponse(ebox_client.ebox_webservice.UploadPkglogItemResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://eboxServic.org/")]
    public partial class UploadPkglogItemResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UploadPkglogItemResult;
        
        public UploadPkglogItemResponseBody() {
        }
        
        public UploadPkglogItemResponseBody(bool UploadPkglogItemResult) {
            this.UploadPkglogItemResult = UploadPkglogItemResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Register_PostmanRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Register_Postman", Namespace="http://eboxServic.org/", Order=0)]
        public ebox_client.ebox_webservice.Register_PostmanRequestBody Body;
        
        public Register_PostmanRequest() {
        }
        
        public Register_PostmanRequest(ebox_client.ebox_webservice.Register_PostmanRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://eboxServic.org/")]
    public partial class Register_PostmanRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PhoneNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Psw;
        
        public Register_PostmanRequestBody() {
        }
        
        public Register_PostmanRequestBody(string PhoneNo, string Psw) {
            this.PhoneNo = PhoneNo;
            this.Psw = Psw;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Register_PostmanResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Register_PostmanResponse", Namespace="http://eboxServic.org/", Order=0)]
        public ebox_client.ebox_webservice.Register_PostmanResponseBody Body;
        
        public Register_PostmanResponse() {
        }
        
        public Register_PostmanResponse(ebox_client.ebox_webservice.Register_PostmanResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://eboxServic.org/")]
    public partial class Register_PostmanResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool Register_PostmanResult;
        
        public Register_PostmanResponseBody() {
        }
        
        public Register_PostmanResponseBody(bool Register_PostmanResult) {
            this.Register_PostmanResult = Register_PostmanResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Postman_SpendRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Postman_Spend", Namespace="http://eboxServic.org/", Order=0)]
        public ebox_client.ebox_webservice.Postman_SpendRequestBody Body;
        
        public Postman_SpendRequest() {
        }
        
        public Postman_SpendRequest(ebox_client.ebox_webservice.Postman_SpendRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://eboxServic.org/")]
    public partial class Postman_SpendRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PhoneNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int cost;
        
        public Postman_SpendRequestBody() {
        }
        
        public Postman_SpendRequestBody(string PhoneNo, int cost) {
            this.PhoneNo = PhoneNo;
            this.cost = cost;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Postman_SpendResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Postman_SpendResponse", Namespace="http://eboxServic.org/", Order=0)]
        public ebox_client.ebox_webservice.Postman_SpendResponseBody Body;
        
        public Postman_SpendResponse() {
        }
        
        public Postman_SpendResponse(ebox_client.ebox_webservice.Postman_SpendResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://eboxServic.org/")]
    public partial class Postman_SpendResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Postman_SpendResult;
        
        public Postman_SpendResponseBody() {
        }
        
        public Postman_SpendResponseBody(int Postman_SpendResult) {
            this.Postman_SpendResult = Postman_SpendResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ebox_serviceSoapChannel : ebox_client.ebox_webservice.ebox_serviceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ebox_serviceSoapClient : System.ServiceModel.ClientBase<ebox_client.ebox_webservice.ebox_serviceSoap>, ebox_client.ebox_webservice.ebox_serviceSoap {
        
        public ebox_serviceSoapClient() {
        }
        
        public ebox_serviceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ebox_serviceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ebox_serviceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ebox_serviceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ebox_client.ebox_webservice.HelloWorldResponse ebox_client.ebox_webservice.ebox_serviceSoap.HelloWorld(ebox_client.ebox_webservice.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ebox_client.ebox_webservice.HelloWorldRequest inValue = new ebox_client.ebox_webservice.HelloWorldRequest();
            inValue.Body = new ebox_client.ebox_webservice.HelloWorldRequestBody();
            ebox_client.ebox_webservice.HelloWorldResponse retVal = ((ebox_client.ebox_webservice.ebox_serviceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        public int add(int a, int b) {
            return base.Channel.add(a, b);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ebox_client.ebox_webservice.Verify_PostmanResponse ebox_client.ebox_webservice.ebox_serviceSoap.Verify_Postman(ebox_client.ebox_webservice.Verify_PostmanRequest request) {
            return base.Channel.Verify_Postman(request);
        }
        
        public int Verify_Postman(string PhoneNo, string Psw) {
            ebox_client.ebox_webservice.Verify_PostmanRequest inValue = new ebox_client.ebox_webservice.Verify_PostmanRequest();
            inValue.Body = new ebox_client.ebox_webservice.Verify_PostmanRequestBody();
            inValue.Body.PhoneNo = PhoneNo;
            inValue.Body.Psw = Psw;
            ebox_client.ebox_webservice.Verify_PostmanResponse retVal = ((ebox_client.ebox_webservice.ebox_serviceSoap)(this)).Verify_Postman(inValue);
            return retVal.Body.Verify_PostmanResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ebox_client.ebox_webservice.Verify_ManagerResponse ebox_client.ebox_webservice.ebox_serviceSoap.Verify_Manager(ebox_client.ebox_webservice.Verify_ManagerRequest request) {
            return base.Channel.Verify_Manager(request);
        }
        
        public bool Verify_Manager(string PhoneNo, string Psw) {
            ebox_client.ebox_webservice.Verify_ManagerRequest inValue = new ebox_client.ebox_webservice.Verify_ManagerRequest();
            inValue.Body = new ebox_client.ebox_webservice.Verify_ManagerRequestBody();
            inValue.Body.PhoneNo = PhoneNo;
            inValue.Body.Psw = Psw;
            ebox_client.ebox_webservice.Verify_ManagerResponse retVal = ((ebox_client.ebox_webservice.ebox_serviceSoap)(this)).Verify_Manager(inValue);
            return retVal.Body.Verify_ManagerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ebox_client.ebox_webservice.UploadPkglogItemResponse ebox_client.ebox_webservice.ebox_serviceSoap.UploadPkglogItem(ebox_client.ebox_webservice.UploadPkglogItemRequest request) {
            return base.Channel.UploadPkglogItem(request);
        }
        
        public bool UploadPkglogItem(string log) {
            ebox_client.ebox_webservice.UploadPkglogItemRequest inValue = new ebox_client.ebox_webservice.UploadPkglogItemRequest();
            inValue.Body = new ebox_client.ebox_webservice.UploadPkglogItemRequestBody();
            inValue.Body.log = log;
            ebox_client.ebox_webservice.UploadPkglogItemResponse retVal = ((ebox_client.ebox_webservice.ebox_serviceSoap)(this)).UploadPkglogItem(inValue);
            return retVal.Body.UploadPkglogItemResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ebox_client.ebox_webservice.Register_PostmanResponse ebox_client.ebox_webservice.ebox_serviceSoap.Register_Postman(ebox_client.ebox_webservice.Register_PostmanRequest request) {
            return base.Channel.Register_Postman(request);
        }
        
        public bool Register_Postman(string PhoneNo, string Psw) {
            ebox_client.ebox_webservice.Register_PostmanRequest inValue = new ebox_client.ebox_webservice.Register_PostmanRequest();
            inValue.Body = new ebox_client.ebox_webservice.Register_PostmanRequestBody();
            inValue.Body.PhoneNo = PhoneNo;
            inValue.Body.Psw = Psw;
            ebox_client.ebox_webservice.Register_PostmanResponse retVal = ((ebox_client.ebox_webservice.ebox_serviceSoap)(this)).Register_Postman(inValue);
            return retVal.Body.Register_PostmanResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ebox_client.ebox_webservice.Postman_SpendResponse ebox_client.ebox_webservice.ebox_serviceSoap.Postman_Spend(ebox_client.ebox_webservice.Postman_SpendRequest request) {
            return base.Channel.Postman_Spend(request);
        }
        
        public int Postman_Spend(string PhoneNo, int cost) {
            ebox_client.ebox_webservice.Postman_SpendRequest inValue = new ebox_client.ebox_webservice.Postman_SpendRequest();
            inValue.Body = new ebox_client.ebox_webservice.Postman_SpendRequestBody();
            inValue.Body.PhoneNo = PhoneNo;
            inValue.Body.cost = cost;
            ebox_client.ebox_webservice.Postman_SpendResponse retVal = ((ebox_client.ebox_webservice.ebox_serviceSoap)(this)).Postman_Spend(inValue);
            return retVal.Body.Postman_SpendResult;
        }
    }
}
